### PR TITLE
[fork] ⚙️ the-gear/ts-lib-starter

### PR DESCRIPTION
**Pull request by langpavel**
This PR is just all what is in [the-gear/ts-lib-starter](https://github.com/the-gear/ts-lib-starter)

You may be interrested in cherry-picking 2be1e788e648a294761a9349b21402a8ab96b09b as it solves #153 

I'm just sharing this — it can be seen as almost rewrite with my custom preferences somewhere.

### CODE REVIEW

**Comment by Hotell** [comment]
Thanks @langpavel ! one suggestion to your "fork".

One suggestion: It would be nice to get some "kudos" to the original author to your "fork" in the README. 👀

**Comment by Hotell** [comment]
I'm gonna close this for now. But please feel free to contribute to relevant things !

Cheers

**Comment by langpavel** [comment]
>  It would be nice to get some "kudos" to the original author to your "fork" in the README.

It is there: [README #Thanks](https://github.com/the-gear/ts-lib-starter/blob/ts-lib-starter/README.md#thanks)
I can reword it if you wish :-)

I want keep your credit in other files, but it's hard as they are inputs for source generation...

**Comment by Hotell** [comment]
aaah didn't see that one ! :) all good

**Pull request closed without merging**
